version: '3'

services:
  go:
    container_name: golang
    image: golang:1.15-alpine
    restart: always
    volumes:
    - .:/app
    working_dir: /app
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  data:
    driver: local
