version: '3'

services:
  go:
    container_name: golang
    image: golang:1.15.1-buster
    command: tail -f /dev/null
    working_dir: /go/src/bot
    volumes:
    - .:/go/src/bot
    networks:
      - app

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
    - ./docker/data/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app

networks:
  app: